-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	username varchar NOT NULL,
	email varchar NOT NULL,
	phone varchar NOT NULL,
	website varchar NULL,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

INSERT INTO public.users ("name",username,email,phone,website,created_at,updated_at) VALUES
	 ('Templeton Greatbank','tgreatbank0','tgreatbank0@china.com.cn','+86 759 127 8484','http://dummyimage.com/108x100.png/cc0000/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Nadeen Mabbe','nmabbe1','nmabbe1@ning.com','+86 500 500 0312','http://dummyimage.com/121x100.png/dddddd/000000','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Brunhilda Nitti','bnitti2','bnitti2@usa.gov','+46 152 624 2428','http://dummyimage.com/205x100.png/ff4444/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Zachariah Dymidowicz','zdymidowicz3','zdymidowicz3@google.com.hk','+86 832 487 2145','http://dummyimage.com/122x100.png/5fa2dd/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Tarra Jone','tjone4','tjone4@1688.com','+63 426 751 9654','http://dummyimage.com/132x100.png/ff4444/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Marguerite Jaegar','mjaegar5','mjaegar5@rediff.com','+46 837 928 7338','http://dummyimage.com/184x100.png/dddddd/000000','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Bron Tocknell','btocknell6','btocknell6@unicef.org','+1 205 377 8556','http://dummyimage.com/133x100.png/5fa2dd/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Andras Pocknell','apocknell7','apocknell7@mail.ru','+52 755 860 9522','http://dummyimage.com/104x100.png/dddddd/000000','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Nedi Paton','npaton8','npaton8@auda.org.au','+1 147 578 3825','http://dummyimage.com/194x100.png/5fa2dd/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Marsh Martynikhin','mmartynikhin9','mmartynikhin9@slashdot.org','+51 377 526 9924','http://dummyimage.com/144x100.png/cc0000/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07');
INSERT INTO public.users ("name",username,email,phone,website,created_at,updated_at) VALUES
	 ('Dewitt Dessant','ddessanta','ddessanta@mayoclinic.com','+229 356 175 2184','http://dummyimage.com/182x100.png/cc0000/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Roanne Ryhorovich','rryhorovichb','rryhorovichb@nhs.uk','+86 664 437 0715','http://dummyimage.com/147x100.png/dddddd/000000','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Gerick Kalinsky','gkalinskyc','gkalinskyc@msn.com','+62 487 257 1168','http://dummyimage.com/150x100.png/cc0000/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Sonja York','syorkd','syorkd@sourceforge.net','+48 851 573 8377','http://dummyimage.com/112x100.png/ff4444/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Phylis Holttom','pholttome','pholttome@marriott.com','+56 862 334 2049','http://dummyimage.com/209x100.png/dddddd/000000','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Hamel Muffett','hmuffettf','hmuffettf@studiopress.com','+86 289 353 0957','http://dummyimage.com/169x100.png/5fa2dd/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Otis Tallquist','otallquistg','otallquistg@dell.com','+81 900 326 5616','http://dummyimage.com/157x100.png/ff4444/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Joell Standring','jstandringh','jstandringh@huffingtonpost.com','+86 793 274 1432','http://dummyimage.com/166x100.png/cc0000/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Karry Gladwell','kgladwelli','kgladwelli@ox.ac.uk','+62 706 428 3577','http://dummyimage.com/224x100.png/ff4444/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07'),
	 ('Appolonia Cork','acorkj','acorkj@ow.ly','+970 424 901 7454','http://dummyimage.com/179x100.png/ff4444/ffffff','2022-08-11 15:05:06.857478+07','2022-08-11 15:05:06.857478+07');
